# yml file for high-level-apps app
stages:
  - deploy

variables:
  DEPLOY_DIR: "/srv/apps"
  DATA_DIR: "/srv/data"

before_script:
   - echo "-- $CI_ENVIRONMENT_NAME deploy --"
   - export PROJECT_DEPLOY_DIR=$DEPLOY_DIR/$CI_ENVIRONMENT_NAME/$CI_PROJECT_NAME
   - mkdir -p $PROJECT_DEPLOY_DIR
   - export VENV_DEPLOY_DIR=$PROJECT_DEPLOY_DIR/VENV

include:
  - project: "gitlab/ci/templates"
    ref: "master"
    file: "gitlab/TriggerPipeline.gitlab-ci.yml"
    
after_script:
   - echo "-- finished $CI_ENVIRONMENT_NAME deploy --"

devel:
 stage: deploy
 tags:
   - hladev-deploy
 script:
   - rm -Rf $PROJECT_DEPLOY_DIR/*
   - cp -R * $PROJECT_DEPLOY_DIR
   - python3 -m venv $VENV_DEPLOY_DIR
   - source $VENV_DEPLOY_DIR/bin/activate
   - pip install -r $PROJECT_DEPLOY_DIR/requirements.txt
   - ln -snf /etc/uwsgi.d/templates/flask-app.ini /etc/uwsgi.d/$CI_ENVIRONMENT_NAME/high-level-apps.ini
 environment:
   name: devel
   url: https://devel.hla.triumf.ca/high-level-apps
 only:
    - devel

# staging:
#  stage: deploy
# tags:
#   - hladev-deploy
#  script:
#    - rm -Rf $PROJECT_DEPLOY_DIR/*
#    - cp -R * $PROJECT_DEPLOY_DIR
#    - python3 -m venv $VENV_DEPLOY_DIR
#    - source $VENV_DEPLOY_DIR/bin/activate
#    - pip install -r $PROJECT_DEPLOY_DIR/requirements.txt
#    - ln -snf /etc/uwsgi.d/templates/flask-app.ini /etc/uwsgi.d/$CI_ENVIRONMENT_NAME/high-level-apps.ini
#  environment:
#    name: staging
#    url: https://staging.hla.triumf.ca/high-level-apps
#  only:
#     - staging

beta:
 stage: deploy
 tags:
   - hladev-deploy
 script:
   - rm -Rf $PROJECT_DEPLOY_DIR/*
   - cp -R * $PROJECT_DEPLOY_DIR
   - python3 -m venv $VENV_DEPLOY_DIR
   - source $VENV_DEPLOY_DIR/bin/activate
   - pip install -r $PROJECT_DEPLOY_DIR/requirements.txt
   - ln -snf /etc/uwsgi.d/templates/flask-app.ini /etc/uwsgi.d/$CI_ENVIRONMENT_NAME/high-level-apps.ini
 environment:
   name: beta
   url: https://beta.hla.triumf.ca/high-level-apps
 only:
    - beta


prod:
  extends: .trigger_pipeline
  stage: deploy
  tags:
    - docker-runner
  only:
    - tags
